//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public string Gender { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public long Phonenumber { get; set; }
        public string Lastname { get; set; }
        public string Firstname { get; set; }
        public int Employeeid { get; set; }
    }
}
